# Generated by Django 4.0.1 on 2022-01-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
