# Generated by Django 4.0.1 on 2022-01-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_product_id_cart_qty_cart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
