# Generated by Django 4.0.1 on 2022-01-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.seller')),
            ],
        ),
    ]
