# Generated by Django 4.0.1 on 2022-01-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
