# Generated by Django 4.0.1 on 2022-01-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_inside1',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='img_inside2',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='img_inside3',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='img_inside4',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='img_inside5',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
