# Generated by Django 4.0.1 on 2022-01-18 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_img_inside1_alter_product_img_inside2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
